config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'lists#index'
  # root to: "movies#index"

  resources :movies, except: :index
  resources :lists
  resources :bookmarks
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :comment, presence: true, length: { minimum: 6 }
  validates :movie_id, uniqueness: { scope: :list_id }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks

  validates :name, uniqueness: true, presence: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks

  validates :title, :overview, presence: true
  validates :title, uniqueness: true
end

##  should not be able to destroy self if has bookmarks children (FAILED - 12)

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    if @bookmark.save
      redirect_to bookmarks_path(@bookmark)
    else render :new
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to movies_path
  end

    private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :list_id, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def new
    @list = List.new
  end

  def show
    @list = List.find(params[:id])
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else render :new
    end
  end

  private

  def list_params
    params.require(:list).permit(:name)
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    @movies = Movie.all
  end

  def new
    @movie = Movie.new
  end

  def show
    @movie = Movie.find(params[:id])
  end

  def create
    # Set the content from the form
    @movie = Movie.new(movies_params)
    @movie.save
    redirect_to movies_path
  end

  private

  def movies_params
  params.require(:movie).permit(:title, :overview, :poster_url, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/bookmarks/new.html.erb
<h1> Create  a bookmark </h1>

<%= simple_form_for @bookmark do |f| %>
  <%= f.input :comment %>
  <%= f.association :movie %>
  <%= f.association :list %>
  <%= f.button :submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<h1> Welcome to lists</h1>

<ol>
 <% @lists.each do |list| %>
 <li><%= list.name%></li>
 <% end %>
</ol>

<%= link_to "Create a list", new_list_path %>

app/views/lists/new.html.erb
<h1> Create  a list </h1>

<%= simple_form_for [ @list ] do |f| %>
  <%= f.input :name %>
  <%= f.submit "Submit list", class: "btn btn-primary" %>
<% end %>

 <%= link_to "back", lists_path %>

app/views/lists/show.html.erb
<h1> One List </h1>


<h2><%= @list.name %></h2>

 <%= link_to "back", lists_path %>

app/views/movies/index.html.erb
<h1> Welcome </h1>

<ol>
 <% @movies.each do |movie| %>
 <li><%= movie.title%></li>
 <% end %>
</ol>

 <%= link_to "Add a new movie", new_movie_path %>

app/views/movies/new.html.erb
<h1> Add  a movie </h1>

<%= simple_form_for [ @movie ] do |f| %>
  <%= f.input :title %>
   <%= f.input :overview %>
    <%= f.input :poster_url %>
    <%= f.input :rating %>
  <%= f.submit "Submit movie", class: "btn btn-primary" %>
<% end %>

 <%= link_to "back", root_path %>

app/views/movies/show.html.erb
<h1> welcome </h1>
<h2> <%= @movie.title %> </h2>

 <%= link_to "back", root_path %>